name = "shoko-labs/shoko"
version = "0.1.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "shoko — on-chain trust layer for indexer claim verification & slashing"

[repository]
user = "shoko-labs"
project = "shoko"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
